services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-monorepo}
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres/postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./infrastructure/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
